### PR TITLE
nzmqt.hpp - add some more MQ constants

### PR DESCRIPTION
**Pull request by mwallnoefer**

### CODE REVIEW

**Comment by machinekoder** [comment]
Is it possible to introduce a ZMQ version check so it does not break compatibility with older ZMQ versions?

**Comment by mwallnoefer** [comment]
As far as I have noticed:
- _ZeroMQ 4.0_ does not provide the ZMQ_TOS flag.
- _ZeroMQ 3.2.6_ (the oldest one I find in the docs) does not provide ZMQ_IMMEDIATE, ZMQ_REQ_CORRELATE, ZMQ_REQ_RELAXED, ZMQ_IPV6, ZMQ_CONFLATE, ZMQ_TOS.

Should we tag these new constants with `#ifdef`s? I think that it would be the simplest solution.

**Comment by machinekoder** [comment]
@mwallnoefer Yes, this would things easier when merging subtrees from upstream.

**Comment by mwallnoefer** [comment]
Upgraded patch, please merge!

**Comment by machinekoder** [comment]
@mwallnoefer Excellent idea!

**Pull request merged**
