### PR TITLE
Update zmq.hpp

### PR DESCRIPTION
**Pull request by mwallnoefer**
This fixes issues like https://github.com/zeromq/cppzmq/issues/40

### CODE REVIEW

**Comment by machinekoder** [comment]
@jonnydee Does fix compile issues on Ubuntu 16.04.

**Comment by mwallnoefer** [comment]
Another fix for size_t - int conversions.

**Comment by mwallnoefer** [comment]
@jonnydee When will you merge my changes?

**Comment by jonnydee** [comment]
Hi, I'm sorry. I merged your changes. Thanks a lot :-)
-- 
Diese EMail ist digital signiert.
This email is digitally signed

----- Original Message -----

**Pull request merged**
