### PR TITLE
implemented SocketNotifierZMQSocket

### PR DESCRIPTION
**Pull request by strahlex**
fixes https://github.com/jonnydee/nzmqt/issues/4

### CODE REVIEW

**Comment by jonnydee** [comment]
Hi Alex, first of all, thank you for your contribution and also for supporting others :-)

Have you checked your solution works with all unit tests? Unfortunately, I am not able to check it myself at the moment...

**Comment by strahlex** [comment]
I tried the unit tests
```
Config: Using QtTest library 5.4.2, Qt 5.4.2 (i386-little_endian-ilp32 shared (dynamic) release build; by GCC 4.6.1)
PASS   : test::NzmqtTest::initTestCase()
PASS   : test::NzmqtTest::testSignalSlotConnections()
QDEBUG : test::NzmqtTest::testPubSub() Publisher>  ("ping", "MSG[1: 2015-11-30T16:59:10]")
QDEBUG : test::NzmqtTest::testPubSub() Subscriber>  ("ping", "MSG[1: 2015-11-30T16:59:10]")
QDEBUG : test::NzmqtTest::testPubSub() Publisher pings sent: 1
QDEBUG : test::NzmqtTest::testPubSub() Subscriber pings received: 1
FAIL!  : test::NzmqtTest::testPubSub() 'spyPublisherPingSent.size() > 3' returned FALSE. (Server didn't send any/enough pings.)
   Loc: [../src/test/nzmqt_test.cpp(162)]
```
Looks like the timer gets stuck.

In my application everything works fine. I am not sure, but the unit tests use additional threads to generate the messages. According to the ZMQ guide using ZMQ sockets in multiple threads is strictly forbidden.

**Comment by strahlex** [comment]
Okay found the problem. The unit tests uses single shot timers. Which use a Qt::DirectConnection to connect signals and slots. However, it looks like a Qt::QueuedConnection is necessary to make it work.

**Comment by strahlex** [comment]
From the Qt docs:
```
Qt::QueuedConnection	2	The slot is invoked when control returns to the event loop of the receiver's thread. The slot is executed in the receiver's thread.
```

**Comment by strahlex** [comment]
The thread objects seems to live in the main thread whereas the socket does not. Looks like the unit tests have a threading problem.

**Comment by jonnydee** [comment]
AFAIK, sockets should not be shared but live in separate threads. The context object on the other hand should be shared by all threads. That's exactly what I tried to do in the unit tests. Did this change in newer releases of ZMQ or am I totally wrong anyway?
Regarding the ConntectionType, yes, this may indeed be a problem. For inter-thread communication queued connections must be used. But I thought 'ConnectionType::Auto' will do this automatically if signal-slot connections between threads are establised...?

**Comment by strahlex** [comment]
It looks like the `createSocket` function is called in the wrong thread. It should be called in `startImpl()` and in the constructor of the `QThread` class.

**Comment by strahlex** [comment]
Turns out that is not the problem.

**Comment by strahlex** [comment]
I have no idea why the singleshot timer is not creating a `Qt::QueuedConnection`. Taking a look at the thread ids it tells me that the slots are executed correctly when `Qt::QueuedConnection` is used. So I suppose enforcing `Qt::QueuedConnection` should solve the problem with the runtests.

**Pull request merged**
